# Server
server:
  port: 9000

# Spring
spring:
  application:
    name: cards
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq: #docker
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted #shutdown
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true #no DNS mapping available in local system, so use ip address
  client:
    fetchRegistry: true #fetch registry information to communicate with other services
    registerWithEureka: true #register in registry on start up
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# management:info
info:
  app:
    name: ${name} #set in settings.gradle
    description: ${name} application
    version: ${version} #set in build.gradle processResources()

# Logging TRACE < DEBUG < INFO < WARN < ERROR
logging:
  level:
    com:
      example:
        cards: DEBUG